### ISSUE TITLE
Unable to find "label.niceToggle" in turn_on_auto_matching()

### ISSUE THREAD

**Issue by akeeton** [tomreece/pucauto#15]
Restarting pucauto fixed this.

```
E:\GitHub\pucauto> python pucauto.py

     _______  __   __  _______  _______  __   __  _______  _______
    |       ||  | |  ||       ||   _   ||  | |  ||       ||       |
    |    _  ||  | |  ||       ||  |_|  ||  | |  ||_     _||   _   |
    |   |_| ||  |_|  ||       ||       ||  |_|  |  |   |  |  | |  |
    |    ___||       ||      _||       ||       |  |   |  |  |_|  |
    |   |    |       ||     |_ |   _   ||       |  |   |  |       |
    |___|    |_______||_______||__| |__||_______|  |___|  |_______|
    www.pucauto.com                                          v0.3.0


Logging in...
Turning on auto matching...
Traceback (most recent call last):
  File "pucauto.py", line 239, in <module>
    main()
  File "pucauto.py", line 228, in main
    turn_on_auto_matching()
  File "pucauto.py", line 62, in turn_on_auto_matching
    DRIVER.find_element_by_css_selector("label.niceToggle").click()
  File "C:\Users\akeeton\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium-2.48.0-py3.5.egg\selenium\webdriver\remote\webdriver.py", line 402, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\akeeton\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium-2.48.0-py3.5.egg\selenium\webdriver\remote\webdriver.py", line 712, in find_element
    {'using': by, 'value': value})['value']
  File "C:\Users\akeeton\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium-2.48.0-py3.5.egg\selenium\webdriver\remote\webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "C:\Users\akeeton\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium-2.48.0-py3.5.egg\selenium\webdriver\remote\errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: {"method":"css selector","selector":"label.niceToggle"}
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///C:/Users/akeeton/AppData/Local/Temp/tmpa4jg43pt/extensions/fxdriver@googlecode.com/components/driver-component.js:10659)
    at FirefoxDriver.prototype.findElement (file:///C:/Users/akeeton/AppData/Local/Temp/tmpa4jg43pt/extensions/fxdriver@googlecode.com/components/driver-component.js:10668)
    at DelayedCommand.prototype.executeInternal_/h (file:///C:/Users/akeeton/AppData/Local/Temp/tmpa4jg43pt/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
    at DelayedCommand.prototype.executeInternal_ (file:///C:/Users/akeeton/AppData/Local/Temp/tmpa4jg43pt/extensions/fxdriver@googlecode.com/components/command-processor.js:12539)
    at DelayedCommand.prototype.execute/< (file:///C:/Users/akeeton/AppData/Local/Temp/tmpa4jg43pt/extensions/fxdriver@googlecode.com/components/command-processor.js:12481)
```

**Comment by tomreece** [comment]
This usually happens when users forget to fill in, or have a typo in, their `config.json` file. Pucauto isn't successfully logging in and thus can't continue any further.

The error message could be a bit more friendly for sure. :) I'll add better error messages, but let me know if you continue to experience this problem.
