### ISSUE TITLE
Crash in filter_trades_dict()

### ISSUE THREAD

**Issue by akeeton** [tomreece/pucauto#16]
```
E:\GitHub\pucauto> python pucauto.py

     _______  __   __  _______  _______  __   __  _______  _______
    |       ||  | |  ||       ||   _   ||  | |  ||       ||       |
    |    _  ||  | |  ||       ||  |_|  ||  | |  ||_     _||   _   |
    |   |_| ||  |_|  ||       ||       ||  |_|  |  |   |  |  | |  |
    |    ___||       ||      _||       ||       |  |   |  |  |_|  |
    |   |    |       ||     |_ |   _   ||       |  |   |  |       |
    |___|    |_______||_______||__| |__||_______|  |___|  |_______|
    www.pucauto.com                                          v0.3.0


Logging in...
Turning on auto matching...
Sorting by member...
Finding trades...
Traceback (most recent call last):
  File "pucauto.py", line 239, in <module>
    main()
  File "pucauto.py", line 236, in main
    find_trades()
  File "pucauto.py", line 216, in find_trades
    valid_trades = filter_trades_dict(trades)
  File "pucauto.py", line 177, in filter_trades_dict
    for member, v in trades.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by XVicarious** [comment]
If you're using Python 3, it no longer has "iteritems" for the dict type.  You have to use Python 2.

**Comment by XVicarious** [comment]
EDIT 2:  Got it.
`trades.iteritems()`
into
`trades.items()`
there is also another instance of this that needs to be changed on line 191.

EDIT: not quite, just tested it and it didn't work.  Trying something else quickly however.

~~Additionally, to make it work on Python 3 the following should work in theory:  
Change
`trades.iteritems()`
into
`trades.items().iter()`~~

**Comment by tomreece** [comment]
Closing this. Thanks @XVicarious for helping out. I'll get PR #19 merged in soon so that folks can use Python 2 or 3. I'll continue a conversation with you there.
