### ISSUE TITLE
Crash when searching for add ons and there are no outgoing trades

### ISSUE THREAD

**Issue by twilightwolf90** [tomreece/pucauto#56]
It appears that when there are no outgoing trades, the bot crashes because the table you are looking for doesn't exist. Line 151 in pucauto.py should have error-check logic (either if-exists or try-catch) to avoid this.  This is in the current branch.  Crash occurred on Debian 8 Jessie.

```
Traceback (most recent call last):
  File "pucauto.py", line 387, in <module>
    find_trades()
  File "pucauto.py", line 350, in find_trades
    find_and_send_add_ons()
  File "pucauto.py", line 151, in find_and_send_add_ons
    DRIVER.find_element_by_css_selector("div.dataTables_filter input").send_keys('Unshipped')
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 402, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 712, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: {"method":"css selector","selector":"div.dataTables_filter input"}
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmpjlp618_e/extensions/fxdriver@googlecode.com/components/driver-component.js:10659)
    at FirefoxDriver.prototype.findElement (file:///tmp/tmpjlp618_e/extensions/fxdriver@googlecode.com/components/driver-component.js:10668)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmpjlp618_e/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
    at DelayedCommand.prototype.executeInternal_ (file:///tmp/tmpjlp618_e/extensions/fxdriver@googlecode.com/components/command-processor.js:12539)
    at DelayedCommand.prototype.execute/< (file:///tmp/tmpjlp618_e/extensions/fxdriver@googlecode.com/components/command-processor.js:12481)
```

**Comment by tomreece** [comment]
Great catch. I missed this because I always have outgoing cards. You should submit a pull request to fix this! The more contributors the better! If you don't want to, let me know so I can fix it. Just wanted to give you a chance to do so. :smile:

**Comment by twilightwolf90** [comment]
Sorry. I can't fix anything this week.  Finals week.

**Comment by tomreece** [comment]
Fixed by https://github.com/tomreece/pucauto/pull/76 which has been merged.
