### ISSUE TITLE
Cloud Server Setup follow-up

### ISSUE THREAD

**Issue by spam8117** [tomreece/pucauto#72]
Hello Tom,
I finally got some time to try out the setup on my seedbox (or raspberry):
https://github.com/tomreece/pucauto/wiki/Cloud-Server-Setup

I ran into some issues, maybe you can help out with some of them :)
1) Seems like Firefox is not possible to install on my distribution, so I needed to install Iceweasel (shouldn't change anything, right?)
2) I did everything until Step 13, but it seems to run into problems:
     _______  __   __  _______  _______  __   __  _______  _______
    |       ||  | |  ||       ||   _   ||  | |  ||       ||       |
    |    _  ||  | |  ||       ||  |_|  ||  | |  ||_     _||   _   |
    |   |_| ||  |_|  ||       ||       ||  |_|  |  |   |  |  | |  |
    |    **_||       ||      _||       ||       |  |   |  |  |_|  |
    |   |    |       ||     |_ |   _   ||       |  |   |  |       |
    |_**|    |_______||_______||**| |**||_______|  |**_|  |____**_|
    pucauto.com                                              v0.4.3
    github.com/tomreece/pucauto
    @pucautobot on Twitter

Logging in...
Traceback (most recent call last):
  File "pucauto.py", line 373, in <module>
    log_in()
  File "pucauto.py", line 59, in log_in
    home_login_div.find_element_by_id("login").send_keys(CONFIG["username"])
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 134, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 474, in find_element
    {"using": by, "value": value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 454, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 188, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: None
<super: <class 'WebDriverException'>, <UnexpectedAlertPresentException object>>
Restarting...
./startup.sh: line 6: killall: command not found
Traceback (most recent call last):
  File "pucauto.py", line 18, in <module>
    DRIVER = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 79, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 49, in **init**
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 106, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmp2PuUVu If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by spam8117** [comment]
Edit: Selenium and Iceweasel seem to work, because if I try this little python script I get the correct output:

from selenium import webdriver
from pyvirtualdisplay import Display

#create virtual display
display = Display(visible=0, size=(800, 600))
display.start()

#make a firefox-instance
browser = webdriver.Firefox()

#open url
browser.get('https://www.smart-itler.de')

print browser.title

**Comment by tomreece** [comment]
@spam8117 The first error `UnexpectedAlertPresentException` is interesting. That makes it sound like when your Iceweasel instance is fired up an alert is present or something unexpected.

Are you 100% sure you started `Xvfb :99 -ac &` and `export DISPLAY=:99` before starting the `./startup.sh` script?

Tell me more about the environment you're trying to run this in and I'll try to reproduce it. It's Debian? What version?

**Comment by tomreece** [comment]
@spam8117 Any news here? I'd like to try to reproduce but need to know more about your environment.

**Comment by tomreece** [comment]
@spam8117 I haven't heard back from you so I'm closing this issue. Will reopen if necessary. :smile:

**Comment by estevopaz** [comment]
Hi, I have the same problem.
It works fine but when the server is CPU overloaded, it crash in same way.
I understand that there is some kind of timeout, how can be modified ?

I answer to myself:

    selenium.webdriver.Firefox(
        firefox_profile=None,
        firefox_binary=None,
        timeout=30,
        capabilities=None,
        proxy=None,
        executable_path='wires',
        firefox_options=None
    )
