### ISSUE TITLE
Crash shortly after startup on Windows with Firefox 45.0.1

### ISSUE THREAD

**Issue by tomreece** [tomreece/pucauto#83]
```
Traceback (most recent call last):
File "C:\Users\username\Desktop\pucauto-master\pucauto.py", line 18, in 
DRIVER = webdriver.Firefox()
File "C:\Users\username\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 77, in __init__
self.binary, timeout),
File "C:\Users\username\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\firefox\extension_connection.py", line 49, in __init__
self.binary.launch_browser(self.profile)
File "C:\Users\username\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 68, in launch_browser
self._wait_until_connectable()
File "C:\Users\username\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 103, in _wait_until_connectable
raise WebDriverException("Can't load the profile. Profile "
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

This can be fixed by running `python -m pip install selenium --upgrade` in cmd.

I'm not sure if it's happening in other environments or not. I'll look into it and perhaps:
- Update the version of selenium in requirements.txt and release a new version of Pucauto
- Send out a newsletter

**Comment by tomreece** [comment]
This is fixed by f9b6cc14488626a368825fda4fff62ed53a06270 and is available in the latest release, v0.4.5, but I'll leave the issue open for a little while in case you find your way here and are looking for a fix.
