### ISSUE TITLE
member_points is occasionally None in build_trades_dict

### ISSUE THREAD

**Issue by tomreece** [tomreece/pucauto#86]
This crash occurs every so often. Not sure what would be causing this to be `None`.

```
Traceback (most recent call last):
  File "pucauto.py", line 397, in <module>
    find_trades()
  File "pucauto.py", line 366, in find_trades
    trades = build_trades_dict(soup)
  File "pucauto.py", line 268, in build_trades_dict
    member_points = int(row.find("td", class_="points").text)
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by xeroiv** [comment]
I am occasionally receiving this error as well.

**Comment by xeroiv** [comment]
I still get this error.  It appears to crash every night sometime between 12:30 AM and 3 AM since I have upgraded to 0.4.9

**Comment by lmjamie** [comment]
This is an almost constant problem. I am lucky if it does not crash overnight due to this issue. Has been for a while
